# Site settings
title: Quantum Life
email: mzb@BigWhy.pro
description: Converting radiation into quantum compute
twitter_username: MarkBruns
github_username:  QTM-life

# Build settings
markdown: kramdown
