# Site settings
title: Quantum Life
email: mzb@BigWhy.pro
description: There's more life in quantum than just computing.
twitter_username: MarkBruns
github_username:  QTM-life

# Build settings
markdown: kramdown
